export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const UPDATE_FIELD = "UPDATE_FIELD";

export const LOGIN = "LOGIN";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOG_OUT_SUCCESS = "SIGN_OUT_SUCCESS";

// CHECKOUT ACTION TYPES 
export const CREDIT_CHECKOUT = "CREDIT_CHECKOUT";
export const CRYPTO_CHECKOUT = "CRYPTO_CHECKOUT";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE";

// CART ACTION TYPES
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"
export const GET_TOTAL = "GET_TOTAL"

// MESSAGE ACTION TYPES
export const CREATE_MESSAGE = "CREATE_MESSAGE"
export const SEND_MESSAGE = "SEND_MESSAGE";

// ERROR ACTION TYPES
export const GET_ERRORS = "GET_ERRORS"
export const RETURN_ERRORS = "RESET_ERROR"