export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
//AUTH ACTION TYPES
export const ERROR_TYPE = "ERROR_TYPE";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOG_OUT_SUCCESS = "SIGN_OUT_SUCCESS";

// CHECKOUT ACTION TYPES
export const CREDIT_CHECKOUT = "CREDIT_CHECKOUT";
export const CREDIT_CHECKOUT_SUCCESS = "CREDIT_CHECKOUT_SUCCESS";
export const CREDIT_CHECKOUT_ERROR = "CREDIT_CHECKOUT_ERROR";
export const CRYPTO_CHECKOUT = "CRYPTO_CHECKOUT";
export const CRYPTO_CHECKOUT_ERROR = "CRYPTO_CHECKOUT_ERROR";
export const CRYPTO_CHECKOUT_SUCCESS = "CRYPTO_CHECKOUT_SUCCESS";

// CART ACTION TYPES
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const GET_TOTAL = "GET_TOTAL";
export const PRE_ORDER = 'PRE_ORDER';
export const PRE_ORDER_SUCCESS = 'PREORDER_SUCCESS';
export const PRE_ORDER_ERROR = "PREORDER_ERROR"

// MESSAGE ACTION TYPES
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const CONTACT_US = "CONTACT_US";
export const CONTACT_US_ERROR = "CONTACT_US_ERROR";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const SEND_EMAIL = "SEND_EMAIL";
export const SEND_EMAIL_ERROR = "SEND_EMAIL_ERROR";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
